### ISSUE TITLE
Resource exhausted

### ISSUE THREAD

**Issue by lzr936332553** [akaraspt/deepsleepnet#25]
Hi Mr.Akaraspt
    I met some error and I don't know how to solve.
    Emmm log is as fallow:

Stats: 
Limit:                   1836384256
InUse:                 1819745536
MaxInUse:          1819745536
NumAllocs:         5133326
MaxAllocSize:     628932608
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************************************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 7.69MiB.  See logs for memory state.

    I use GTX1050 to ran it.And my memory is 2G.Maybe it's small.
    But I'm sorry to bother you. And can you help me solve this problem？Thank you for reading this.: )

**Comment by lzr936332553** [comment]
Traceback (most recent call last):
  File "train.py", line 95, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 90, in main
    n_epochs=FLAGS.finetune_epochs
  File "train.py", line 72, in finetune
    resume=FLAGS.resume
  File "/home/lzr/桌面/deepsleepnet-master/deepsleep/trainer.py", line 712, in finetune
    is_train=True
  File "/home/lzr/桌面/deepsleepnet-master/deepsleep/trainer.py", line 524, in _run_epoch
    feed_dict=feed_dict
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: <exception str() failed>

This is traceback. : )

**Comment by akaraspt** [comment]
I think you have to reduce the `batch_size` as your GPU has the limit amount of space.

**Comment by lzr936332553** [comment]
I reduced it but the traceback is same.Even if I go down to the minimum --batch_size=1. I don't know why .But I Changed your code to run pretrain by gpu run finetune by cpu . But the computer is very noisy and it takes too much time .I don't think my cpu can stand it . Can you give me another question ?                  
And now a question suddenly occurred to me . If I use your code can I get the sleep staging results for the edf specified?

**Comment by lzr936332553** [comment]
I have run your project . Thank you so much . : ).Your code has helped me a lot
