### ISSUE TITLE
Problem in prepare_physionet.py

### ISSUE THREAD

**Issue by newace0127** [akaraspt/deepsleepnet#28]
Hello akaraspt,

Thank you for your contribution. I got the following error when trying to run the code:

Traceback (most recent call last):
  File "prepare_physionet.py", line 15, in <module>
    from mne import Epochs, pick_types, find_events
  File "L:\Programs\anaconda3\envs\env_py2\lib\site-packages\mne\__init__.py", line 22, in <module>
    from .utils import (set_log_level, set_log_file, verbose, set_config,
  File "L:\Programs\anaconda3\envs\env_py2\lib\site-packages\mne\utils\__init__.py", line 23, in <module>
    from .fetching import _fetch_file, _url_to_local_path
  File "L:\Programs\anaconda3\envs\env_py2\lib\site-packages\mne\utils\fetching.py", line 11, in <module>
    from urllib import parse, request
ImportError: cannot import name parse

It seems the dependency library is out of date? Is there any way to counter the problem?
Thank you so much.

**Comment by akaraspt** [comment]
Did you use a different version of Python? The repo is written with Python 2.7.
