### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xe4 in position 2050: illegal multibyte sequence

### ISSUE THREAD

**Issue by 647LiuSQ** [akaraspt/deepsleepnet#30]
I get the following when I run the code:

Traceback (most recent call last):
<_io.TextIOWrapper name='.\\data\\physionet_sleep\\SC4001E0-PSG.edf' mode='r' encoding='cp936'>
  File "D:/report/deepsleepnet-master/prepare_physionet.py", line 229, in <module>
    main()
  File "D:/report/deepsleepnet-master/prepare_physionet.py", line 112, in main
    reader_raw.read_header()
  File "D:\report\deepsleepnet-master\dhedfreader.py", line 90, in read_header
    self.header = h = edf_header(self.file)
  File "D:\report\deepsleepnet-master\dhedfreader.py", line 46, in edf_header
    assert f.read(8) == '0       '
UnicodeDecodeError: 'gbk' codec can't decode byte 0xe4 in position 2050: illegal multibyte sequence

**Comment by akaraspt** [comment]
I think you might be using different versions (probably the new ones) from the ones specified in the repo.

Try to install the packages with the version specified [here](https://github.com/akaraspt/deepsleepnet#environment), then let me know whether this helps.

**Comment by czhao1986** [comment]
The same problem is encountered and solved. 
Solution: python version must be 2.7 and mne version is 0.17.
