### ISSUE TITLE
ZeroDivisionError: float modulo

### ISSUE THREAD

**Issue by Irving-ren** [akaraspt/deepsleepnet#32]
Hi, Akaraspt. Thanks for sharing your script. 

I got this error while running the following script.  
python prepare_physionet.py --data_dir data --output_dir data/eeg_fpz_cz --select_ch 'EEG Fpz-Cz'. 
Error info:
Traceback (most recent call last):
  File "<pudb command line>", line 1, in <module>
  File "/home/irving/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 498, in split
    if N % sections:
ZeroDivisionError: float modulo

As you saw, the error was self-understanding. After debugging, I have traced the reason for this error is happening from line 168 of prepare_physionet.py, which the variable n_trims was assigned to 0. I was understanding the previous code's function is finding useful data with labels. However, I am still confused about this error. Do you have any idea the reason for this part?  I am really appreciative of it.

Best wishes,
Irving

**Comment by akaraspt** [comment]
Do you use the same version for all required Python package?

**Comment by Irving-ren** [comment]
Sorry for the late replying. I was using the exact same pkgs you mentioned before. Is there any update about those pkgs?

Best,
Irving
