### ISSUE TITLE
Problems in Prepare_physionet

### ISSUE THREAD

**Issue by JiangPeiy** [akaraspt/deepsleepnet#38]
/Users/apple/.conda/envs/EEG_classification/bin/python /Users/apple/PycharmProjects/deepsleepnet/prepare_physionet.py
Traceback (most recent call last):
  File "/Users/apple/PycharmProjects/deepsleepnet/prepare_physionet.py", line 217, in <module>
    main()
  File "/Users/apple/PycharmProjects/deepsleepnet/prepare_physionet.py", line 72, in main
    os.makedirs(args.output_dir)
  File "/Users/apple/.conda/envs/EEG_classification/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/apple/.conda/envs/EEG_classification/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/apple/.conda/envs/EEG_classification/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

Process finished with exit code 1

Here is the problem that I met and I tried many ways like sodu  but it did not work.

**Comment by besaman** [comment]
looks like you don't have a '/data' folder ??
